name: Build and Deploy

on:
    push:
        branches: [cicd]

jobs:
    build:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout code
              uses: actions/checkout@v2

            - name: Setup Node.js
              uses: actions/setup-node@v2
              with:
                  node-version: 18.16

            - name: Install dependencies
              run: |
                  cd frontend
                  npm install

            - name: Build React app
              run: |
                  cd frontend
                  pwd
                  ls -al
                  npm run build
